# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wa-210-300621-mueller-luuk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr300621210.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6353e32e551d4ea896a205fa4fdedd2f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_92798ecba64e4f52b4dc9f1f66e6d481 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6353e32e551d4ea896a205fa4fdedd2f }}/todo-app:${{ github.sha }}
        file: ./src/backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wa-210-300621-mueller-luuk'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f53ee7e9468a45aea23c310796ccd988 }}
        images: 'acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6353e32e551d4ea896a205fa4fdedd2f }}/todo-app:${{ github.sha }}'
