name: Build and Deploy Docker App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: 'acr300621210.azurecr.io'
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/todo-app:${{ github.sha }}
        context: ./src/backend
        file: ./src/backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wa-210-300621-mueller-luuk'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: 'acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/todo-app:${{ github.sha }}'
